---

библиотека Numpy и линейная алгебра


In [1]:
import numpy as np
import random
import scipy.stats as sps

### Numpy

### Задание 1
В первой задаче вам предлагается перемножить две квадратные матрицы двумя способами -- без использования пакета ***numpy*** и с ним.

In [2]:
a = np.random.sample((100, 100))
b = np.random.sample((100, 100))

print(a)
print(b)

[[0.50721446 0.13010375 0.56079029 ... 0.11739027 0.91329646 0.50048389]
 [0.33210145 0.43346584 0.488255   ... 0.34626022 0.68387701 0.45755397]
 [0.82753224 0.09293742 0.27760024 ... 0.40742023 0.84860379 0.98784904]
 ...
 [0.41564137 0.37419007 0.76073607 ... 0.11621673 0.06903585 0.31820983]
 [0.19312092 0.75204522 0.92598002 ... 0.36987287 0.08626834 0.49689541]
 [0.71321982 0.4127667  0.89125408 ... 0.91370715 0.87689189 0.22603405]]
[[0.13383781 0.93989992 0.34996094 ... 0.77866224 0.82153822 0.12738374]
 [0.97980043 0.38360763 0.88310126 ... 0.70799698 0.59679242 0.29799293]
 [0.63562761 0.47843834 0.08479996 ... 0.94148075 0.69063186 0.0382195 ]
 ...
 [0.45954851 0.15003065 0.80485593 ... 0.72296596 0.30149856 0.48822584]
 [0.32716899 0.96398441 0.43144535 ... 0.26929937 0.04517573 0.94026327]
 [0.72900258 0.27298927 0.62754944 ... 0.42641102 0.36583148 0.7924864 ]]


In [3]:
def mult(a, b):
   
    c = [[0 for _ in range(len(a))] for _ in range(len(b[0]))]
    for i in range(len(a)):
        for j in range(len(b)):
            for k in range(len(a[0])):
                c[i][j] += a[i][k] * b[k][j]
    return c

In [4]:
def np_mult(a, b):
    
    return a @ b

In [5]:
%%time

M1 = mult(a, b)

CPU times: total: 1.22 s
Wall time: 1.28 s


In [6]:
%%time
# засечем время работы функции с NumPy
M2 = np_mult(a, b)

CPU times: total: 0 ns
Wall time: 6.99 ms


In [7]:
np.abs(np.array(M1) - M2).sum()

1.4729550912306877e-11

### Задание 2
Напишите функцию, которая по данной последовательности $\{A_i\}_{i=1}^n$ строит последовательность $S_n$, где $S_k = \frac{A_1 + ... + A_k}{k}$.  
Аналогично -- с помощью библиотеки **NumPy** и без нее. Сравните скорость.

In [8]:
# функция, решающая задачу с помощью NumPy
def sec_av(A):
    return np.cumsum(A) / np.arange(1, len(A)+1)

In [9]:
# функция без NumPy
def stupid_sec_av(A):
    S = [sum(A[:i+1])/(i+1) for i in range(len(A))]
    return S

In [10]:
# зададим некоторую последовательность и проверим ее на ваших функциях. 
# вторая функция должна работать ~ в 50 раз быстрее
A = sps.uniform.rvs(size=10**3) 

%time S1 = stupid_sec_av(A)
%time S2 = sec_av(A)
# проверим корректность (последовательности должны совпадать, т.е. разность равна 0):
np.abs(S1 - S2).sum()

CPU times: total: 109 ms
Wall time: 88 ms
CPU times: total: 0 ns
Wall time: 0 ns


0.0

### Задание 3

Пусть задан некоторый массив $X$. Надо построить новый массив, где все элементы с нечетными индексами требуется заменить на число $a$ (если оно не указано, то на 1). Все четные элементы исходного массива нужно возвести в куб и записать в обратном порядке относительно позиций этих элементов. Массив $X$ при этом должен остаться *без изменений*. В конце требуется слить массив X с преобразованным X и вывести в обратном порядке.  

Пример:  
X = [100, 200, 300, 400, 500] -> [100, a, 300, a, 500] -> [500^3, a, 300^3, a, 100^3] -> склеиваем -> [100, 200, 300, 400, 500, 500^3, a, 300^3, a, 100^3]

In [11]:
# функция, решающая задачу с помощью NumPy
def transformation(X, a=1):
    N = np.array(X[::-1])
    N[1::2] = a
    N[::2] = N[::2] ** 3
    return np.hstack((np.array(X) , N))

In [12]:
# функция, решающая задачу  без NumPy
def stupid_transformation(X, a=1):
    N = X[::-1]
    N[1::2] = [a for _ in range(len(N[1::2]))]
    N[::2] = [x**3 for x in N[::2]]
    return X + N

In [13]:
X = [i for i in range(10, 1000, 10)]
# здесь код должен быть эффективнее примерно в 20 раз. 
%time S1 = stupid_transformation(X)
%time S2 = transformation(X)
# проверим корректность:
np.abs(S1 - S2).sum()

CPU times: total: 0 ns
Wall time: 0 ns
CPU times: total: 0 ns
Wall time: 0 ns


0

Почему методы ***numpy*** оказываются эффективнее (можно гуглить)?

Что вы можете сказать о скорости вычислений в NumPy? Ответ обоснуйте.

**Ответ:** Скорость вычислений вектоных и матричных операций в NumPy сильно превосходит скорость вычислений без него, по большей части потому, что функции numpy работаю с массивами данных одного типа (числовыми), это позволяет реализовать встроенные функции numpy на C/C++, что, конечно, делает numpy быстрее (функции, которые вызывает Numpy для работы с числовыми данными, сильно оптимизированы именно под эти задачи, а сам Python просто гоняет интерпретатор по циклу в таких операциях, что является чуть ли не самым большим замедлением в работе интерпретатора).

### Задание 4

Вам подаются на вход два вектора `a` и `b` в трехмерном пространстве.Заполните их случайными числами. Реализуйте их скалярное произведение с помощью  `NumPy` и без. Засеките время работы, как это показано в заданиях выше.

In [14]:
a = np.random.sample((1, 3))
a = list(a)[0]
b = np.random.sample((1, 3))
b = list(b)[0]
print(a, b)

[0.37839767 0.49356166 0.35140624] [0.55887287 0.45707705 0.77514939]


In [15]:
def stupid_scalar_product(a,b):
    return sum([x * y for (x, y) in zip(a, b)])

In [16]:
def numpy_scalar_product(a,b):
    return a @ b

In [17]:
%time product_1 = stupid_scalar_product(a,b)
%time product_2 = numpy_scalar_product(a,b)
# проверим корректность:
np.abs(product_1 - product_2).sum()

CPU times: total: 0 ns
Wall time: 0 ns
CPU times: total: 0 ns
Wall time: 0 ns


0.0

### Задание 5*

Нужно написать матричное произведение БЕЗ циклов и БЕЗ символа @, БЕЗ `np.dot` и вообще БЕЗ какой-либо вспомогательной функции из `numpy`, то есть пользуясь только индексированием, взятем суммы по нужным осям и поэлементным произведенем (да, это возможно). Рекомендуем гуглить по запросу "NumPy broadcasting"

In [19]:
def cool_matrix_product(A, B):
    # налейте чаю, удобно присядьте и просто осознайте это :)
    # (на самом деле просто распишите, что получается про numpy broadcasting)
    return (A[:,:, None] * B[None,:,:]).sum(axis=1)  

In [20]:
A = np.random.sample((100, 100))
B = np.random.sample((100, 100))

In [22]:
np.sum(A@B - cool_matrix_product(A, B), axis=0)

array([ 3.19744231e-14, -2.48689958e-14,  3.90798505e-14, -4.97379915e-14,
       -3.19744231e-14,  2.13162821e-14, -2.13162821e-14,  1.77635684e-14,
       -2.48689958e-14,  1.77635684e-14,  3.55271368e-15,  1.06581410e-14,
       -1.42108547e-14, -1.77635684e-14,  4.26325641e-14, -3.55271368e-15,
       -1.77635684e-14,  3.19744231e-14,  2.84217094e-14, -2.13162821e-14,
        1.42108547e-14,  1.42108547e-14, -7.10542736e-15, -3.19744231e-14,
        1.06581410e-14, -3.55271368e-15, -1.06581410e-14, -2.48689958e-14,
       -2.48689958e-14,  1.42108547e-14,  4.97379915e-14,  1.06581410e-14,
       -3.55271368e-15,  6.75015599e-14, -2.84217094e-14, -7.10542736e-14,
       -1.77635684e-14,  2.84217094e-14,  1.06581410e-14,  3.19744231e-14,
        1.42108547e-14, -5.68434189e-14, -1.06581410e-14,  3.19744231e-14,
       -1.42108547e-14,  2.48689958e-14, -5.68434189e-14,  0.00000000e+00,
        2.84217094e-14,  2.48689958e-14, -1.77635684e-14, -3.55271368e-14,
       -2.84217094e-14, -

(машинный ноль)